name: env_stateact
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.10.16
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.2
      - airportsdata==20241001
      - annotated-types==0.7.0
      - anyio==4.8.0
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==24.3.0
      - blake3==1.0.2
      - cachetools==5.5.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorful==0.5.6
      - compressed-tensors==0.8.1
      - depyf==0.18.0
      - dill==0.3.9
      - diskcache==5.6.3
      - distlib==0.3.9
      - distro==1.9.0
      - einops==0.8.0
      - exceptiongroup==1.2.2
      - fastapi==0.115.6
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - gguf==0.10.0
      - google-api-core==2.24.0
      - google-auth==2.37.0
      - googleapis-common-protos==1.66.0
      - grpcio==1.69.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.27.1
      - idna==3.10
      - importlib-metadata==8.5.0
      - iniconfig==2.0.0
      - interegular==0.3.3
      - jinja2==3.1.5
      - jiter==0.8.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - lark==1.2.2
      - linkify-it-py==2.0.3
      - lm-format-enforcer==0.10.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - memray==1.15.0
      - mistral-common==1.5.1
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.1.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.59.7
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python-headless==4.11.0.86
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==24.2
      - partial-json-parser==0.2.1.1.post5
      - pillow==10.4.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.0.2
      - propcache==0.2.1
      - proto-plus==1.25.0
      - protobuf==5.29.3
      - psutil==6.1.1
      - py-cpuinfo==9.0.0
      - py-spy==0.4.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pybind11==2.13.6
      - pycountry==24.6.1
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pytest==8.3.4
      - python-dotenv==1.0.1
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - ray==2.40.0
      - referencing==0.36.1
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.22.3
      - rsa==4.9
      - safetensors==0.5.2
      - sentencepiece==0.2.0
      - six==1.17.0
      - smart-open==7.1.0
      - sniffio==1.3.1
      - starlette==0.41.3
      - sympy==1.13.1
      - textual==1.0.0
      - tiktoken==0.7.0
      - tokenizers==0.21.0
      - tomli==2.2.1
      - torch==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.48.0
      - triton==3.1.0
      - typing-extensions==4.12.2
      - uc-micro-py==1.0.3
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - virtualenv==20.29.0
      - vllm==0.6.6.post1
      - watchfiles==1.0.4
      - websockets==14.1
      - wrapt==1.17.2
      - xformers==0.0.28.post3
      - xgrammar==0.1.10
      - yarl==1.18.3
      - zipp==3.21.0
